capstoneproject/Controllers/sksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using capstoneproject.Models;

namespace capstoneproject.Controllers
{
    public class sksController : Controller
    {
        private schoolsEntities1 db = new schoolsEntities1();

        // GET: sks
        [Authorize]
        public ActionResult Index()
        {
            return View(db.sks.ToList());
        }

        // GET: sks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sk sk = db.sks.Find(id);
            if (sk == null)
            {
                return HttpNotFound();
            }
            return View(sk);
        }

        // GET: sks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: sks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name")] sk sk)
        {
            if (ModelState.IsValid)
            {
                db.sks.Add(sk);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sk);
        }

        // GET: sks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sk sk = db.sks.Find(id);
            if (sk == null)
            {
                return HttpNotFound();
            }
            return View(sk);
        }

        // POST: sks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name")] sk sk)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sk).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sk);
        }

        // GET: sks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sk sk = db.sks.Find(id);
            if (sk == null)
            {
                return HttpNotFound();
            }
            return View(sk);
        }

        // POST: sks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            sk sk = db.sks.Find(id);
            db.sks.Remove(sk);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

capstoneproject/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

capstoneproject/Views/Shared/_Layout.cshtml
<html>
<head>
    <title>School</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/main.css" rel="stylesheet" />
    @RenderSection("Styles", false)
    @RenderSection("Scripts", required: false)

</head>
<body class="subpage">



    <!-- Header -->
    <header id="header" class="alt">

        <div class="logo"><a href="index.html">@ViewBag.Title</div>

        <a href="#menu"><span>Menu</span></a>

    </header>
    <!-- Nav -->
    <nav id="menu">

        <ul class="links">

            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("About", "About", "Home")</li>
            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            <li>@Html.ActionLink("Admin", "Index", "sks")</li>




        </ul>

    </nav>


    @RenderBody()

    <footer id="footer">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()


        <div class="inner">

            <h2>Having a problem with this site? </h2>
            <center><strong><p>Type whats wrong & send a message</p></strong></center>


            <div class="field half">
                <center><font color="White">Name</font></center>

                <div class="col-md-10">
                    <center><input type="text" /></center>
                </div>
            </div>

            <div class="field half">
                <center><font color="White">Email</font></center>
                <div class="col-md-10">
                    <center><input type="text" /></center>
                </div>
            </div>

            <div class="field">
                <center><font color="White">Message</font></center>
                <div class="col-md-10">
                    <center><textarea></textarea></center>
                </div>
            </div>

            <div class="field">
                <center>
                    <input value="Send Message" class="button alt" type="submit"/>
                  </center>
                  </div>


                    <ul class="icons">
                        <li><a href="#" class="icon round fa-twitter"><span class="label">Twitter</span></a></li>
                        <li><a href="#" class="icon round fa-facebook"><span class="label">Facebook</span></a></li>
                        <li><a href="#" class="icon round fa-instagram"><span class="label">Instagram</span></a></li>
                    </ul>

            </div>
}
</footer>

    <!-- Scripts -->
    <script src="~/Scripts/jquery.min.js"></script>

    <script src="~/Scripts/jquery.scrolly.min.js"></script>

    <script src="~/Scripts/jquery.scrollex.min.js"></script>

    <script src="~/Scripts/skel.min.js"></script>

    <script src="~/Scripts/util.js"></script>

    <script src="~/Scripts/main.js"></script>


</body>
</html>