capstoneproject/Models/zc.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capstoneproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zc
    {
        public int zipcode { get; set; }
        public Nullable<int> skid { get; set; }
    
        public virtual sk sk { get; set; }
    }
}

capstoneproject/Controllers/zcsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using capstoneproject.Models;

namespace capstoneproject.Controllers
{
    public class zcsController : Controller
    {
        private schoolsEntities db = new schoolsEntities();

        // GET: zcs
        public ActionResult Index()
        {
            var zcs = db.zcs.Include(z => z.sk);
            return View(zcs.ToList());
        }

        //[HttpPost]
        public ActionResult Search(int zipcode)
        {
            var zc = db.zcs.Find(zipcode);

            if (zc == null)
                return View("Index");
            var districtName = zc.sk.name;
          
            return View(districtName);
           
        }


        // GET: zcs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            zc zc = db.zcs.Find(id);
            if (zc == null)
            {
                return HttpNotFound();
            }
            return View(zc);
        }

        // GET: zcs/Create
        public ActionResult Create()
        {
            ViewBag.skid = new SelectList(db.sks, "id", "name");
            return View();
        }

        // POST: zcs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "zipcode,skid")] zc zc)
        {
            if (ModelState.IsValid)
            {
                db.zcs.Add(zc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.skid = new SelectList(db.sks, "id", "name", zc.skid);
            return View(zc);
        }

        // GET: zcs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            zc zc = db.zcs.Find(id);
            if (zc == null)
            {
                return HttpNotFound();
            }
            ViewBag.skid = new SelectList(db.sks, "id", "name", zc.skid);
            return View(zc);
        }

        // POST: zcs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "zipcode,skid")] zc zc)
        {
            if (ModelState.IsValid)
            {
                db.Entry(zc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.skid = new SelectList(db.sks, "id", "name", zc.skid);
            return View(zc);
        }

        // GET: zcs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            zc zc = db.zcs.Find(id);
            if (zc == null)
            {
                return HttpNotFound();
            }
            return View(zc);
        }

        // POST: zcs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            zc zc = db.zcs.Find(id);
            db.zcs.Remove(zc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

capstoneproject/Views/zcs/Create.cshtml
@model capstoneproject.Models.zc

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>zc</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.zipcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.zipcode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.zipcode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.skid, "skid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("skid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.skid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

capstoneproject/Views/zcs/Delete.cshtml
@model capstoneproject.Models.zc

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>zc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.sk.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sk.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

capstoneproject/Views/zcs/Details.cshtml
@model capstoneproject.Models.zc

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>zc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.sk.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sk.name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.zipcode }) |
    @Html.ActionLink("Back to List", "Index")
</p>

capstoneproject/Views/zcs/Edit.cshtml
@model capstoneproject.Models.zc

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>zc</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.zipcode)

        <div class="form-group">
            @Html.LabelFor(model => model.skid, "skid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("skid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.skid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

capstoneproject/Views/zcs/Hazelwood.cshtml
@{
    ViewBag.Title = "Hazelwood";
}
<section id="post" class="wrapper bg-img" data-bg="h.png">
    <div class="inner">
        <article class="box">
            <header>
                <center><h2>Hazelwood</h2></center>
                <p></p>
            </header>
            <center><strong><font color="white"> About Hazelwood District Schools</strong> </font></center>

            <center><p><strong><font color="white">Hazelwood School District is Fully Accredited by the Missouri Department of Elementary and Secondary Education  </strong> </font> </p></center>
            </header>

            <center><strong><Header> <font color="white"> Rate of the Hazelwood </Header><strong></center></font>
            <center>
                <p><font color="white"> Hazelwood School District's rating is 4 with a Graduation rate of 85.7% </p></font><center>

                    <center>
                        <strong>
                            <Header><font color="white"> How many students attend (ditstict, school, class) </Header><strong>
                                <center>
                                    </font>
                                    <p /><font color="white">
                                        Hazelwood School District is a school district with 18,118 students.The school has 336 students per school. & about 15-30 students per class</p><font>

                                            <center><strong><Header><font color="white"> How much money the district spends per student </Header></strong></center>
                                        </font>
                                        <p><font color="white">Hazelwood School District spends $8,191 per year per student</p>
                                    </font>


                                    <p><a style="color : blue" href="https://www.hazelwoodschools.org"> HazelwoodSchools.com</a> </p>

capstoneproject/Views/zcs/Index - Copy.cshtml
@model IEnumerable<capstoneproject.Models.zc>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.sk.name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.sk.name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.zipcode }) |
            @Html.ActionLink("Details", "Details", new { id=item.zipcode }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.zipcode })
        </td>
    </tr>
}

</table>

capstoneproject/Views/zcs/Index.cshtml
@model capstoneproject.Models.zc

@{
    ViewBag.Title = "Home Page";
}
@section Styles {
    <link href="~/Content/popup.css" rel="stylesheet" />
}

<!-- Banner -->
<!--
    Note: To show a background image, set the "data-bg" attribute below
    to the full filename of your image. This is used in each section to set
    the background image.
-->
<section id="banner" class="bg-img" data-bg="ff.jpg">
    <div class="inner">
        <header>
            <h1>Welcome to Grade for Grades</h1>
            <strong><p>Where you can find education for your kids</p></strong>
            <ul class="actions">
                @*<link href="~/Content/popup.css" rel="stylesheet" />*@
                <!--div class=" box"-->
                <!--div class=" box"-->
                <li><a class="big button" href="#popup1">Get  Started </a></li>
                <!--</div>-->
                <!--><div id="popup1" class="overlay"><!-->
                <li>
                    <div class="popup">
                        @using (Html.BeginForm("Search", "zcs", FormMethod.Get))
                        {
                            <h2 style="color : black">Please Enter Your Zip Code </h2>
                            <a class="close" href="#">&times;</a>
                            <div class="content">
                                @Html.EditorFor(model => model.zipcode, new { htmlAttributes = new { @class = "form-control" } })

                                <br>

                                <input type="submit" value="Submit">

                            </div>
                        }
                    </div>
                </li>
            </ul>
        </header>

    </div>


</section>
<ul class="actions">


    @*<link href="~/Content/popup.css" rel="stylesheet" />*@


    <!--<a href="#one" class="more">Learn More</a>-->
    </section>

    <!-- One -->
    <section id="one" class="wrapper post bg-img" data-bg="pk.jpg">
        <div class="inner">
            <article class="box">
                <header>
                    <h2>About Grade for Grades</h2>
                </header>
                <div class="content">
                    <p><font color="white"> Grade for Grades has the soul purpouse to help find out what school diatrict you in but ultimately help you find a school to enroll your child or children in. </font></p>
                </div>
                <footer>
                    <a href="~/Home/About" class="button alt">Learn More</a>

                </footer>
            </article>
        </div>
        <!--<a href="#two" class="more">Learn More</a> -->
    </section>

    <!-- Two -->
    <section id="two" class="wrapper post bg-img" data-bg="ed.png">
        <!-- <div class="inner">
                <article class="box">
                    <header>
                        <h2>Mus elit a ultricies at</h2>
                        <p>12.21.2016</p>
                    </header>
                    <div class="content">
                        <p>Scelerisque enim mi curae erat ultricies lobortis donec velit in per cum consectetur purus a enim platea vestibulum lacinia et elit ante scelerisque vestibulum. At urna condimentum sed vulputate a duis in senectus ullamcorper lacus cubilia consectetur odio proin sociosqu a parturient nam ac blandit praesent aptent. Eros dignissim mus mauris a natoque ad suspendisse nulla a urna in tincidunt tristique enim arcu litora scelerisque eros suspendisse.</p>
                    </div>
                    <footer>
                        <a href="generic.html" class="button alt">Learn More</a>
                    </footer>
                </article>
            </div>
            <a href="#three" class="more">Learn More</a>
        </section> -->

capstoneproject/Views/zcs/McCluer.cshtml
@{
    ViewBag.Title = "McCluer";
}


<section id="post" class="wrapper bg-img" data-bg="m.png">
    <div class="inner">
        <article class="box">
            <header>
                <center><h2>McCluer</h2></center>
                <p></p>
            </header>


           <header> <center><strong><font color="white"> About McCluer District Schools</strong> </font></center>

            <center><p><strong><font color="white">McCluer School District is fully Accredited by the Missouri Department of Elementary and Secondary Education  </strong> </font> </p> </center>
            </header>

            <center><strong><Header> <font color="white"> Rate of the Riverview school district </Header></strong></center></font>
            <center>
                <p><font color="white"> McCluer School District's rating is 1 with a Graduation rate of 73% </p></font></center>

                    <center>
                        <strong>
                            <Header><font color="white"> How many students attend (ditstict, school, class) </Header><strong>
                                <center>
                                    </font>
                                    <p /><font color="white">
                                        McCluer School District is a school district with 6,180 students.The school has 306 students per school. & about 15-30 students per class</p><font>

                                            <center><strong><Header><font color="white"> How much money the district spends per student </Header></strong></center>
                                        </font>
                                        <p><font color="white">McCluer School District spends $8,120 per year per student</p>
                                    </font>



                                    <p><a style="color : blue" href="https://www.fergflor.org"> McCluerSchools.com</a> </p>

capstoneproject/Views/zcs/Riverview.cshtml
@{
    ViewBag.Title = "Riverview";
}


<section id="post" class="wrapper bg-img" data-bg="r.png">
    <div class="inner">
        <article class="box">
            <center><strong><font color="white"> About Riverview District Schools</strong> </font></center>

            <center><p><strong><font color="white">Riverview School District is not Accredited by the Missouri Department of Elementary and Secondary Education  </strong> </font> </p></center>
            </header>

            <center><strong><Header> <font color="white"> Rate of the Riverview school district </Header><strong></center></font>
            <center>
                <p><font color="white"> Riverview School District's rating is 1 with a Graduation rate of 58% </p></font><center>

                    <center>
                        <strong>
                            <Header><font color="white"> How many students attend (ditstict, school, class) </Header><strong>
                                <center>
                                    </font>
                                    <p /><font color="white">
                                        Riverview School District is a school district with 6,020 students.The school has 336 students per school. & about 15-30 students per class</p><font>

                                            <center><strong><Header><font color="white"> How much money the district spends per student </Header></strong></center>
                                        </font>
                                        <p><font color="white">Riverview School District spends $8,120 per year per student</p>
                                    </font>



                                    </header>
                                    <p><a style="color : blue" href="http://www.rgsd.k12.mo.us/"> RiverviewSchools.com</a> </p>
   